const TEAM_META: Record<string, { flag: string; code: string }> = {
  Brazil: { flag: "🇧🇷", code: "BRA" },
  Morocco: { flag: "🇲🇦", code: "MAR" },
  Serbia: { flag: "🇷🇸", code: "SRB" },
  Cameroon: { flag: "🇨🇲", code: "CMR" },
  Argentina: { flag: "🇦🇷", code: "ARG" },
  Spain: { flag: "🇪🇸", code: "ESP" },
  Iran: { flag: "🇮🇷", code: "IRN" },
  Senegal: { flag: "🇸🇳", code: "SEN" },
  France: { flag: "🇫🇷", code: "FRA" },
  Netherlands: { flag: "🇳🇱", code: "NED" },
  Mexico: { flag: "🇲🇽", code: "MEX" },
  Tunisia: { flag: "🇹🇳", code: "TUN" },
  "United States": { flag: "🇺🇸", code: "USA" },
  Germany: { flag: "🇩🇪", code: "GER" },
  Japan: { flag: "🇯🇵", code: "JPN" },
  Wales: { flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", code: "WAL" },
  England: { flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", code: "ENG" },
  Belgium: { flag: "🇧🇪", code: "BEL" },
  Australia: { flag: "🇦🇺", code: "AUS" },
  Egypt: { flag: "🇪🇬", code: "EGY" },
  Portugal: { flag: "🇵🇹", code: "POR" },
  Italy: { flag: "🇮🇹", code: "ITA" },
  "South Korea": { flag: "🇰🇷", code: "KOR" },
  Algeria: { flag: "🇩🇿", code: "ALG" },
  Croatia: { flag: "🇭🇷", code: "CRO" },
  Uruguay: { flag: "🇺🇾", code: "URU" },
  Poland: { flag: "🇵🇱", code: "POL" },
  "Ivory Coast": { flag: "🇨🇮", code: "CIV" },
  Switzerland: { flag: "🇨🇭", code: "SUI" },
  Denmark: { flag: "🇩🇰", code: "DEN" },
  Colombia: { flag: "🇨🇴", code: "COL" },
  Nigeria: { flag: "🇳🇬", code: "NGA" },
  Sweden: { flag: "🇸🇪", code: "SWE" },
  Ukraine: { flag: "🇺🇦", code: "UKR" },
  "Türkiye": { flag: "🇹🇷", code: "TUR" },
  Turkey: { flag: "🇹🇷", code: "TUR" },
  Chile: { flag: "🇨🇱", code: "CHI" },
  Norway: { flag: "🇳🇴", code: "NOR" },
  Austria: { flag: "🇦🇹", code: "AUT" },
  Czechia: { flag: "🇨🇿", code: "CZE" },
  Ecuador: { flag: "🇪🇨", code: "ECU" },
  Hungary: { flag: "🇭🇺", code: "HUN" },
  Romania: { flag: "🇷🇴", code: "ROU" },
  Greece: { flag: "🇬🇷", code: "GRE" },
  Scotland: { flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", code: "SCO" },
  Slovakia: { flag: "🇸🇰", code: "SVK" },
  Canada: { flag: "🇨🇦", code: "CAN" },
  Ghana: { flag: "🇬🇭", code: "GHA" },
  Peru: { flag: "🇵🇪", code: "PER" },
};

export function teamMeta(name: string): { flag: string; code: string } {
  return TEAM_META[name] ?? { flag: "🏳️", code: name.slice(0, 3).toUpperCase() };
}
